// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (uuid.UUID, error)
	GetCustomer(ctx context.Context, id uuid.UUID) (Customer, error)
	ListCustomers(ctx context.Context) ([]Customer, error)
}

var _ Querier = (*Queries)(nil)
